version: "3.9"
services:
  postgres:
    container_name: epsirum
    image: postgres
    environment:
      - POSTGRES_USER=epsilono
      - POSTGRES_PASSWORD=epsilono
      - POSTGRES_DB=epsirum_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
volumes:
  postgres_data:
